### ISSUE TITLE
config.yml not found on build

### ISSUE THREAD

**Issue by theantidoak** [CodeStitchOfficial/Intermediate-Website-Kit-SASS#1]
Hi,

I'm getting this error when trying to access <my-site>.netlify.app/admin. localhost:8080/admin works fine.

Page Error:

Error loading the CMS configuration
Config Errors:
Error: Failed to load config.yml (404)
Check your config.yml file.

Browser Dev Tools Console Error:

Failed to load resource: the server responded with a status of 404 ()
config.js:439 Uncaught (in promise) Error: Failed to load config.yml (404)
    at F (config.js:439:11)
    at async config.js:570:68
    
I haven't made any changes to the project, but I have followed the instructions (except step 1 about filling out robot.txt, sitemap.xml, and _redirects) according to the README.md:

2. Navigate to your Netlify Admin Panel, click _Add new site | Import an existing project_
3. Follow the instructions to connect your GitHub repository to Netlify. Most of the site settings should be done for you, thanks to `netlify.toml`
4. Once deployed, click on _Identity_ in the top navigation, then click _Enable Identity_
5. Invite yourself, and the client, to the site
6. While in the Identity tab, click the "Settings and usage" button to open the settings options. Then, do the following:
    - Find "Registration Preferences", click "Edit Settings" and set registration from _Public_ to _Invite Only_
    - Find "Enable Providers" and add a provider. We recommend Google, so the client can login with Google in 1 click.
    - Find "Git Gateway" and enable it

 
 Summary: No project changes have been made. localhost:8080/admin and <my-site>.netlify.app work. 
 
 <my-site>.netifly.app/admin does not work and gives the above error.

**Comment by CodeStitchOfficial** [comment]
Hey thanks for reaching out!Unfortunately, it seems as if this is a fairly common issue with DecapCMS - the content management provider for the build kits. There appears to be a bug where the CMS boots up on a "/#" path, which leads to the error that you're likely seeing.The fix for this is to make sure the end of the URL reads '/#/'. A bit of an annoyance, but a fix nonetheless. We’re hoping they patch this up in future updates. If this doesn't fix your issues, let us know and we'll be happy to take another look for you.Thanks,Ryan P.On Jul 29, 2023, at 9:05 AM, theantidoak ***@***.***> wrote:﻿
Hi,
I'm getting this error when trying to access .netlify.app/admin. localhost:8080/admin works fine.
Page Error:
Error loading the CMS configuration
Config Errors:
Error: Failed to load config.yml (404)
Check your config.yml file.
Browser Dev Tools Console Error:
Failed to load resource: the server responded with a status of 404 ()
config.js:439 Uncaught (in promise) Error: Failed to load config.yml (404)
at F (config.js:439:11)
at async config.js:570:68
I haven't made any changes to the project, but I have followed the instructions (except step 1 about filling out robot.txt, sitemap.xml, and _redirects) according to the README.md:

Navigate to your Netlify Admin Panel, click Add new site | Import an existing project
Follow the instructions to connect your GitHub repository to Netlify. Most of the site settings should be done for you, thanks to netlify.toml
Once deployed, click on Identity in the top navigation, then click Enable Identity
Invite yourself, and the client, to the site
While in the Identity tab, click the "Settings and usage" button to open the settings options. Then, do the following:

Find "Registration Preferences", click "Edit Settings" and set registration from Public to Invite Only
Find "Enable Providers" and add a provider. We recommend Google, so the client can login with Google in 1 click.
Find "Git Gateway" and enable it



Summary: No project changes have been made. localhost:8080/admin and .netlify.app work.
.netifly.app/admin does not work and gives the above error.

**Comment by theantidoak** [comment]
Thanks! I recently tried to set up a configuration with nunjucks. It wasn't great, so I'm loving going through your configuration.

**Comment by CodeStitchOfficial** [comment]
Hello!

Apologies it's taken so long to come up with a fix. I reached out to the Decap team to see if they could fix the issue natively, but they've been (understandably) busy with other Decap things.

Fortunately, a kind member of our community, @clsscrchm, contributed a PR to patch things within the starter kits. You should be able to copy/paste the script in the latest commit, add it to the <head> of your admin/index.html file, and have it work!

``` 
<script>
    (function() {
        if (!location.href.endsWith('/')) {
            window.location = location.href + '/'
        }
    }());
</script>
```

Going to happily close this one, and thank everyone for raising and fixing the issue
